# This is a basic workflow to help you get started with Actions

name: Remote Testing for React

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["**"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test-Submit-React-Assessments:
    name: Run Super Duper React Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Echoing version
        run: echo hello world
