#repo version 2.0.1
name: Remote Testing for React 

on:
   push:
     branches:
       - "**"
  workflow_dispatch:

jobs:
  Test-Submit-React-Assessments:
    name: Run Super Duper React Tests
    runs-on: self-hosted
    steps:
      run: echo npm @testing-library/react version 
        
     
    
#   
