# This is a basic workflow to help you get started with Actions

name: Remote Testing for React

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: ["yml-edit4"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Test-Submit-React-Assessments:
    name: Run Super Duper React Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check react version
        run: echo "$(npm show react version)"

      - name: Check react testing library
        run: echo "$(npm show @testing-library/react version)"

      - uses: actions/checkout@v2
      - name: Test using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - run: |
          yarn install
          yarn test

      - name: Build app
        run: yarn build
#
